added environment setter

diff --git a/.github/workflows/tyk-lint.yml b/.github/workflows/tyk-lint.yml
--- a/.github/workflows/tyk-lint.yml
+++ b/.github/workflows/tyk-lint.yml
@@ -46,19 +46,19 @@ jobs:
     #     which jq
     #     jq --version
     
-    # - name: Determine Environment
-    #   id: determine_environment
-    #   run: |
-    #       if [[ "${{ github.event_name }}" == "workflow_call" ]]; then
-    #         # Workflow called with an input
-    #         echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
-    #       elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
-    #         # Workflow called with an input
-    #         echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
-    #       else
-    #         echo "environment=dev" >> $GITHUB_ENV
-    #         echo "Error: No environment has been specified. Setting to dev environment." >&2
-    #       fi
+    - name: Determine Environment
+      id: determine_environment
+      run: |
+          if [[ "${{ github.event_name }}" == "workflow_call" ]]; then
+            # Workflow called with an input
+            echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
+          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            # Workflow called with an input
+            echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
+          else
+            echo "environment=dev" >> $GITHUB_ENV
+            echo "Error: No environment has been specified. Setting to dev environment." >&2
+          fi
 
     - name: Lint API Definitions
       uses: stoplightio/spectral-action@latest
