updated linter logic

diff --git a/.github/workflows/tyk-schema-validation.yml b/.github/workflows/tyk-schema-validation.yml
--- a/.github/workflows/tyk-schema-validation.yml
+++ b/.github/workflows/tyk-schema-validation.yml
@@ -9,20 +9,20 @@ on:
       - 'dev/**'
       - 'stg/**'
       - 'prod/**'
-  workflow_dispatch:
-    inputs:
-      environment: 
-        type: choice
-        options:
-          - stg
-          - prod
+  # workflow_dispatch:
+  #   inputs:
+  #     environment: 
+  #       type: choice
+  #       options:
+  #         - stg
+  #         - prod
   workflow_call:
     inputs:
       environment:
         type: string
 
 jobs:
-  schema-validation:
+  schema-linter-and-validation:
     runs-on: ubuntu-latest
     
     steps:
@@ -46,37 +46,59 @@ jobs:
         which jq
         jq --version
     
-    # Execute Spectral / Stoplight plugin to validate Tyk APIs
-    - name: Run API Linter and Validate Required Fields
+    - name: Determine Environment
+      id: determine_environment
+      run: |
+          if [[ "${{ github.event_name }}" == "workflow_call" ]]; then
+            # Workflow called with an input
+            echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
+          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            # Workflow called with an input
+            echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
+          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            # Determine which directory to process based on modified files
+            MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
+            echo $MODIFIED_FILES
+            if echo "$MODIFIED_FILES" | grep -q '^infrastructure/staging/tyk/'; then
+              echo "environment=staging" >> $GITHUB_ENV
+            elif echo "$MODIFIED_FILES" | grep -q '^infrastructure/production/tyk/'; then
+              echo "environment=production" >> $GITHUB_ENV
+            else
+              echo "Error: No relevant files modified in the pull request." >&2
+              exit 1
+            fi
+          fi
+
+    - name: Lint API Definitions
       uses: stoplightio/spectral-action@latest
       with:
-          file_glob: ${{ env.environment }}/apis/api-*.json
-          spectral_ruleset: ${{ env.environment }}/tykapi-ruleset.yaml
-      continue-on-error: false
+        file_glob: ${{ env.environment }}/apis/api-*.json
+        spectral_ruleset: ${{ env.environment }}/tykapi-ruleset.yaml
+      continue-on-error: true
 
-    # Tyk API Linting and API Governance for Minimum Required Fields
-    - name: 'Validate min fields for APIs and Policies'
-      run: |
-        cd ./dev
-        for file in $(find . -name "*.json"); do
-            echo "Validating API/Policy definition $file"
+    # # Tyk API Linting and API Governance for Minimum Required Fields
+    # - name: 'Validate min fields for APIs and Policies'
+    #   run: |
+    #     cd ./dev
+    #     for file in $(find . -name "*.json"); do
+    #         echo "Validating API/Policy definition $file"
             
-            # Check if target_url is valid and not empty
-            if jq -e '.proxy.target_url | length > 0' "$file" > /dev/null; then
-              echo "$file contains a valid proxy.target_url."
-              target_url=$(jq -r '.proxy.target_url' "$file")
-              echo "proxy.target_url: $target_url"
-            else
-              echo "$file does NOT contain a valid proxy.target_url."
-              exit 1
-            fi
+    #         # Check if target_url is valid and not empty
+    #         if jq -e '.proxy.target_url | length > 0' "$file" > /dev/null; then
+    #           echo "$file contains a valid proxy.target_url."
+    #           target_url=$(jq -r '.proxy.target_url' "$file")
+    #           echo "proxy.target_url: $target_url"
+    #         else
+    #           echo "$file does NOT contain a valid proxy.target_url."
+    #           exit 1
+    #         fi
             
-            # Check if either JWT auth or or MutuatTLS is enabled
-            if jq -e '.enable_jwt == true or .auth_configs.use_mutual_tls_auth == true' "$file" > /dev/null; then
-              echo "$file has either enable_jwt or auth_configs.use_mutual_tls_auth set to true."
-            else
-              echo "$file does NOT have either enable_jwt or auth_configs.use_mutual_tls_auth set to true."
-              exit 1
-            fi
+    #         # Check if either JWT auth or or MutuatTLS is enabled
+    #         if jq -e '.enable_jwt == true or .auth_configs.use_mutual_tls_auth == true' "$file" > /dev/null; then
+    #           echo "$file has either enable_jwt or auth_configs.use_mutual_tls_auth set to true."
+    #         else
+    #           echo "$file does NOT have either enable_jwt or auth_configs.use_mutual_tls_auth set to true."
+    #           exit 1
+    #         fi
             
-          done
+    #       done
